// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.EfCore;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    partial class EF_DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.EfCore.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Smartphones and futuristic mobile devices",
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laptops and portable computers",
                            Name = "Laptop"
                        });
                });

            modelBuilder.Entity("WebApi.EfCore.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientNumber")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WantsNewsletter")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApi.EfCore.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "/img/1mobil.webp",
                            Name = "Futuristic Smartphone 1",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa001"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "/img/2mobil.webp",
                            Name = "Futuristic Smartphone 2",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa002"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageUrl = "/img/3mobil.webp",
                            Name = "Futuristic Smartphone 3",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa003"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageUrl = "/img/4mobil.webp",
                            Name = "Futuristic Smartphone 4",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa004"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImageUrl = "/img/5mobil.webp",
                            Name = "Futuristic Smartphone 5",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa005"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ImageUrl = "/img/6mobil.webp",
                            Name = "Futuristic Smartphone 6",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa006"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ImageUrl = "/img/7mobil.webp",
                            Name = "Futuristic Smartphone 7",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa007"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ImageUrl = "/img/8mobil.webp",
                            Name = "Futuristic Smartphone 8",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa008"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ImageUrl = "/img/9mobil.webp",
                            Name = "Futuristic Smartphone 9",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa009"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ImageUrl = "/img/10mobil.webp",
                            Name = "Futuristic Smartphone 10",
                            Price = 1000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "aaa010"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ImageUrl = "/img/1laptop.webp",
                            Name = "Gaming Laptop 1",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb001"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            ImageUrl = "/img/2laptop.webp",
                            Name = "Gaming Laptop 2",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb002"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ImageUrl = "/img/3laptop.webp",
                            Name = "Gaming Laptop 3",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb003"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ImageUrl = "/img/4laptop.webp",
                            Name = "Gaming Laptop 4",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb004"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            ImageUrl = "/img/5laptop.webp",
                            Name = "Gaming Laptop 5",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb005"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ImageUrl = "/img/6laptop.webp",
                            Name = "Gaming Laptop 6",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb006"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ImageUrl = "/img/7laptop.webp",
                            Name = "Gaming Laptop 7",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb007"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            ImageUrl = "/img/8laptop.webp",
                            Name = "Gaming Laptop 8",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb008"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ImageUrl = "/img/9laptop.webp",
                            Name = "Gaming Laptop 9",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb009"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ImageUrl = "/img/10laptop.webp",
                            Name = "Gaming Laptop 10",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb010"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            ImageUrl = "/img/11laptop.webp",
                            Name = "Gaming Laptop 11",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb011"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            ImageUrl = "/img/12laptop.webp",
                            Name = "Gaming Laptop 12",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb012"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            ImageUrl = "/img/13laptop.webp",
                            Name = "Gaming Laptop 13",
                            Price = 2000m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sku = "bbb013"
                        });
                });

            modelBuilder.Entity("WebApi.EfCore.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SaleNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("WebApi.EfCore.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceUnit")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("WebApi.EfCore.Product", b =>
                {
                    b.HasOne("WebApi.EfCore.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApi.EfCore.Sale", b =>
                {
                    b.HasOne("WebApi.EfCore.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApi.EfCore.SaleItem", b =>
                {
                    b.HasOne("WebApi.EfCore.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("WebApi.EfCore.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.EfCore.Client", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("WebApi.EfCore.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
